name: Update Index.json

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Update index
        run: node dist/index.js

      - name: Add File
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .

      - name: Check is need to push
        id: check_status
        run: |
          STATUS=$(git status --porcelain | wc -l)
          echo "number of files that need to be committed:" $STATUS
          echo "::set-output name=STATUS::$STATUS"

      - name: Commit File
        if: steps.check_status.outputs.STATUS > 0
        run: |
          echo "status"
          now=$(date)
          git commit -m "Auto Commit $now"
      - name: Push Changes
        if: steps.check_status.outputs.STATUS > 0
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
